spring:
  application:
    name: member-management
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    return-instance-for-empty-row: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

